version: '3'

services:
  mariadb:
    image: 'mariadb:10.3'
    container_name: mysql.crm
    ports:
    - "3306:3306"
    volumes:
    - db:/var/lib/mysql:Z
    environment:
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=suitecrmdb

  app:
    build: ./app
    container_name: suitecrm.crm
    depends_on:
    - mariadb
    tty: true
    volumes:
      - suitecrm:/var/www/html
    environment:
    - CURRENCY_ISO4217=EUR
    - CURRENCY_NAME=Euro
    - DATE_FORMAT=d-m-Y
    - EXPORT_CHARSET=ISO-8859-1
    - DEFAULT_LANGUAGE=en_us
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=mariadb
    - DB_ADMIN_PASSWORD=secret
    - DB_ADMIN_USERNAME=admin
    - DATABASE_NAME=suitecrmdb
    - SITE_USERNAME=admin
    - SITE_PASSWORD=password
    - SITE_URL=http://localhost
    - SYSTEM_NAME=delight photography CRM

  web:
    build: ./web
    restart: always
    ports:
      - 8080:80
    volumes:
      - suitecrm:/var/www/html:ro
    depends_on:
      - app

volumes:
    db:
    suitecrm:
