version: '3'

services:
  mariadb:
    image: 'mariadb:10.3'
    container_name: mariadb.crm
    ports:
    - "3306:3306"
    volumes:
    - db:/var/lib/mysql:Z
    environment:
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbuserpass
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=crmdb

  app:
    build: ./app
    container_name: suitecrm.crm
    depends_on:
    - mariadb
    tty: true
    volumes:
      - suitecrm:/var/www/html
      - suitecrm-confg:/var/www/html/conf.d

  web:
    build: ./web
    container_name: nginx.crm
    restart: always
    ports:
      - 8080:80
    volumes:
      - suitecrm:/var/www/html:ro
    depends_on:
      - app

volumes:
    db:
    suitecrm:
    suitecrm-confg:
